#pragma config(Sensor, dgtl1, solenoidRight,  sensorDigitalOut)
#pragma config(Sensor, dgtl2, solenoidLeft,   sensorDigitalOut)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(0)
#pragma userControlDuration(60)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                         Driver Skills Template
//
// This is a template for the driver skills competition. It is identical in structure to
// the standard competition template except that the two "#pragma' statements above (and
// copied below) adjust the time limits for the competition.
//				#pragma autonomousDuration(0)
//				#pragma userControlDuration(60)
// The autonomous duration for "Driver Skills" is zero; i.e. there is no autonomous phase.
// The user control duration is 60 seconds
//
// NOTE: The above two pragmas only impact the Crystal implementation. For systems using
//       VEXNET, the VEXNET system ignores these statements as it has the durations
//       for the competition built-in.
//
// Whenever this user program is run, the duration is automatically sent to the VEX master
// processor. The master CPU will only accept these commands once per power=on cycle. So, it's
// best to power cycle your VEX to ensure that they get recognized in case you were
// previously running a standard competition program with different durations.
//
// Testing Via Crystals:
// ====================
//
// The procedure to test a Driver Skills program using the crystals is as follows:
//
// 1. Turn off power to the Crystal transmitter/joysticks.
//
// 2. Turn on your VEX so that the Driver Skills program is running.
//
// 3. Driver skills program segment of your program will start running. At the end of 60
//    seconds the VEX Master CPU will turn off the motors.
//
// 4. Repeat the above sequence
//
//
// Testing Via VEXNET Using VEXNET Competition Switch
// ==================================================
//
// The procedure to test a Driver Skills program using VEXNET Competition Switch is as follows:
//
// 1. Set the two switches on the Competition switch to "DISABLE" and "USER CONTROL"
//
// 2. Start the Driver skills program
//
// 3. Set Switch to ENABLE from DISABLE
//
// 4. You need to manually time the 60 second duration.
//
// 5. Set Switch to DISABLE
//
// 6. Repeat from step (3) to run subsequent test runs. There's no need to reset the VEX or
//    restart your user program.
//
//
// Testing Via VEXNET Using ROBOTC IDE
// ==================================================
//
// It is not necessary to own a VEXNET switch. ROBOTC has a test window that allows the same functionality.
// The test window has three buttons for "DISABLE", "AUTONOMOUS", "USER CONTROL".
//
// 1. Open the ROBOTC Debugger. Then open the "Competition Control" Debugger window.
//
// 2. Start your Driver Skills program running.
//
// 3. Click the "DISABLED" button on the "Competition Control" window.
//
// 4. Click the "USER CONTROL" button on the "Competition Control" window.
//
// 5. You need to manually time the 60 second duration.
//
// 6. Click the "DISABLED" button on the "Competition Control" window.
//
// 7. Repeat from step (4) to run subsequent test runs. There's no need to reset the VEX or
//    restart your user program.
//
/////////////////////////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////
// Forward is how much forward, right is how much right, yawPower is how much power to turn with
// Why the fk do you need do differnt powers and then add them, just use one lol -Ashish Shrestha
void move(int forward, int yawPower) {
	motor[port4] =   forward + yawPower;
	motor[port5] =   forward + yawPower;
	motor[port6] = - forward + yawPower;
	motor[port7] = - forward + yawPower;
}

// Controls the lift
void lift(int power) {
	motor[port1] = power; //Yes this is correct, don't touch it, it works just fine
	motor[port2] = -power;
	motor[port3] = -power;
	motor[port8] = power;
	motor[port9] = power;
	motor[port10] = power;
}

void pneumaticClaw(bool direction) {
	SensorValue[solenoidRight] = direction; // Goes in ports 1 and 2
	SensorValue[solenoidLeft] = direction;
}
void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// The "Driver Skills" competition has no autonomous phase. Simply leave the following
// placeholder.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	// robot is starting from the right, use bottom code when from the left
	// Drop forklift from locked position
	move(-127, 0);
	lift(63);
	wait1Msec(250);
	lift(-127);
	move(127, 0);
	wait1Msec(250);
	lift(0);

	// Move back and then forward to grab stars
	move(-127,0);
	wait1Msec(500); // Change depending on amount of time it takes for forklift to get off of the stars
	pneumaticClaw(true);
	move(127,0);
	wait1Msec(1500); // Change depending on amount of time it takes to scoop up the stars in front of it.
	pneumaticClaw(false);
	move(-127,0);
	wait1Msec(750);
	move(0,127);
	lift(10);
	wait1Msec(650); // Change depending on amount of time it takes to rotate 90 degrees
	/* Uncomment this if you want to lift the stars before moving
	lift(63);
	wait1Msec(250);
	lift(10);
	*/
	// Move forward with grabbed stars
	move(127,0);
	wait1Msec(1500);
	move(0,127);
	wait1Msec(1450); // Just a bit too long

	// Dump stars
	move(-127,0);
	lift(127);
	wait1Msec(500);
	pneumaticClaw(true);
	lift(0);
		/* Commented out for testing purposes
	move(0,127);
	wait1Msec(700);

	move(-127,0);
	wait1Msec(2000);

	move(0,-127);
	wait1Msec(700);

	move(127,0);
	wait1Msec(3500);
	pneumaticClaw(false);
	move(-127,0);
	wait1Msec(3500);
	move(-127,0);
	lift(127);
	wait1Msec(500);
	pneumaticClaw(true);
	lift(0); */
	lift(0);
	move(0,0);
	pneumaticClaw(false);
	/*while (true)
	{

	}*/
}
